/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://umv3d3xtljfddgzwtm7tpldsde.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5lfb5trlpfcetbattisp6ignpi",
    "aws_cognito_identity_pool_id": "us-east-2:5c6964e2-b1c4-4e17-ac61-7c7372d6a74b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_vXyciZEaE",
    "aws_user_pools_web_client_id": "4jpfp0492jls1llti5ap6vn48k",
    "oauth": {
        "domain": "dseehappy-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dseehappy.com/signin/",
        "redirectSignOut": "https://dseehappy.coml/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
